# Generated by Django 5.2.12 on 2026-04-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_user_admin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('hod', 'HOD'), ('admin', 'Admin')], max_length=10),
        ),
    ]
