# Generated by Django 5.2.12 on 2026-04-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_faculty_fa_subject_fields'),
        ('users', '0006_alter_user_role'),
    ]

    operations = [
    ]
