# Generated by Django 5.2.12 on 2026-04-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_year_fields_choices'),
        ('users', '0007_merge_20260415_0728'),
    ]

    operations = [
    ]
