# Generated by Django 4.2 on 2026-05-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20260415_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arrears_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_arrears',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='job_offers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty_advisor_class',
            field=models.CharField(blank=True, help_text='Class or section managed by the Faculty (FA)', max_length=100, null=True, verbose_name='Faculty (FA) Advisor Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty_fa_department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('MECHANICAL', 'MECHANICAL')], max_length=15, null=True, verbose_name='Faculty (FA) Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty_fa_from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Faculty (FA) From Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty_fa_section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Faculty (FA) Section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty_fa_to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Faculty (FA) To Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_faculty_fa',
            field=models.BooleanField(default=False, help_text='Mark this user as Faculty (FA) advisor', verbose_name='Faculty (FA)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subject_holder',
            field=models.BooleanField(default=False, help_text='Mark this user as Faculty (Subject Holder)', verbose_name='Faculty (Subject Holder)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('hod', 'HOD'), ('placement_officer', 'Placement Officer'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject_holder_class_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of classes handled as a subject holder', null=True, verbose_name='Subject Holder Class Count'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject_holder_department',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('MECHANICAL', 'MECHANICAL')], max_length=15, null=True, verbose_name='Subject Holder Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject_holder_section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Subject Holder Section'),
        ),
    ]
