# Generated by Django 4.2 on 2026-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_arrears_history_user_cgpa_user_current_arrears_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_placement_officer',
            field=models.BooleanField(default=False, help_text='Mark this user as Placement Officer', verbose_name='Placement Officer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('hod', 'HOD'), ('admin', 'Admin')], max_length=20),
        ),
    ]
