# Generated by Django 4.2 on 2026-05-02 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_placement_officer_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=3)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('MECHANICAL', 'MECHANICAL')], max_length=15)),
                ('designation', models.CharField(choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('hod', 'HOD'), ('other', 'Other')], max_length=50)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('joining_year', models.CharField(max_length=4)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
