# Generated by Django 4.2 on 2026-05-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_staffregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisor_faculty_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='register_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_joining',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='designation',
            field=models.CharField(choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('hod', 'HOD'), ('faculty_fa', 'Faculty (FA)'), ('faculty_subject', 'Faculty (Subject Holder)'), ('librarian', 'Librarian'), ('placement_officer', 'Placement Officer'), ('association_advisor', 'Association Advisor'), ('hostel_warden', 'Hostel Warden'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('hod', 'HOD'), ('faculty_fa', 'Faculty (FA)'), ('faculty_subject', 'Faculty (Subject Holder)'), ('librarian', 'Librarian'), ('placement_officer', 'Placement Officer'), ('association_advisor', 'Association Advisor'), ('hostel_warden', 'Hostel Warden'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
