# Generated by Django 4.2 on 2026-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_advisor_faculty_id_user_age_user_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='account_approval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='appointment_order',
            field=models.FileField(blank=True, null=True, upload_to='staff_registration/appointment_orders/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='association_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='block_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='class_incharge_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='companies_coordinated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='department_managed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='duty_timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='floor_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='hostel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='staff_registration/id_cards/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='industry_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='library_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='official_whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='staff_registration/profile_photos/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='qualification_certificates',
            field=models.FileField(blank=True, null=True, upload_to='staff_registration/qualification_certificates/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='staff_registration/resumes/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='section_managed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='semester_handling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='shift_timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='subjects_handled',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
