# Generated by Django 5.0.1 on 2026-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_staffregistration_account_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='temporary_assignment_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='temporary_assignment_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
