# Generated by Django 5.2.12 on 2026-03-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='student',
        ),
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.CharField(default='CSE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='CSE', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(choices=[('9:00-9:50', '9:00-9:50'), ('9:50-10:40', '9:50-10:40'), ('11:00-11:50', '11:00-11:50'), ('11:50-12:40', '11:50-12:40'), ('1:25-2:15', '1:25-2:15'), ('2:15-3:05', '2:15-3:05'), ('3:20-4:10', '3:20-4:10'), ('4:10-5:00', '4:10-5:00')], max_length=20),
        ),
    ]
