# Generated by Django 5.2.12 on 2026-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_notification_file_notification_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='role',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
