# Generated by Django 5.2.12 on 2026-03-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_timetable_student_timetable_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], default='CSE', max_length=10),
        ),
    ]
