# Generated by Django 5.2.12 on 2026-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_timetable_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=1)),
                ('section', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='assignments/')),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
