# Generated by Django 5.2.12 on 2026-03-27 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_notification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='department',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='section',
            field=models.CharField(default='CSE', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='year',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
