# Generated by Django 5.2.12 on 2026-04-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_notification_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], default='CSE', max_length=10)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('exam_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('internal', 'Internal')], max_length=20)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('time_period', models.CharField(max_length=100)),
                ('faculty', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_arrangement', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
