# Generated by Django 5.2.12 on 2026-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_examtimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='semester_subject_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
