# Generated by Django 5.2.12 on 2026-04-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_examtimetable_semester_subject_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.CharField(choices=[('P1', 'Period 1 (9:00-9:50)'), ('P2', 'Period 2 (9:50-10:40)'), ('P3', 'Period 3 (10:55-11:45)'), ('P4', 'Period 4 (11:45-12:35)'), ('P5', 'Period 5 (1:25-2:15)'), ('P6', 'Period 6 (2:15-3:05)'), ('P7', 'Period 7 (3:20-4:10)'), ('P8', 'Period 8 (4:10-5:00)')], default='P1', max_length=3),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(choices=[('9:00-9:50', '9:00-9:50'), ('9:50-10:40', '9:50-10:40'), ('11:00-11:50', '11:00-11:50'), ('11:50-12:40', '11:50-12:40'), ('1:25-2:15', '1:25-2:15'), ('2:15-3:05', '2:15-3:05'), ('3:20-4:10', '3:20-4:10'), ('4:10-5:00', '4:10-5:00')], default='9:00-9:50', max_length=20),
        ),
    ]
