# Generated by Django 5.2.12 on 2026-04-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_add_subject_code_to_timetable'),
        ('students', '0011_timetable_credits_timetable_period_and_more'),
    ]

    operations = []
