# Generated by Django 5.2.12 on 2026-04-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('inter_college', 'Inter College Events'), ('external_college', 'External College Events'), ('common', 'Common Notification')], default='common', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
