# Generated by Django 5.2.12 on 2026-04-12 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamTimetable',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='period',
            field=models.CharField(choices=[('P1', 'Period 1'), ('P2', 'Period 2'), ('P3', 'Period 3'), ('P4', 'Period 4'), ('P5', 'Period 5'), ('P6', 'Period 6'), ('P7', 'Period 7'), ('P8', 'Period 8')], default='P1', max_length=3),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(choices=[('9:00-9:50', '9:00-9:50'), ('9:50-10:40', '9:50-10:40'), ('11:00-11:50', '11:00-11:50'), ('11:50-12:40', '11:50-12:40'), ('1:25-2:15', '1:25-2:15'), ('2:15-3:05', '2:15-3:05'), ('3:20-4:10', '3:20-4:10'), ('4:10-5:00', '4:10-5:00')], max_length=20),
        ),
    ]
