# Generated by Django 5.2.12 on 2026-04-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_delete_examtimetable_remove_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='form_type',
            field=models.CharField(choices=[('semester', 'Semester Feedback'), ('event', 'Event Feedback'), ('course', 'Course Feedback'), ('faculty', 'Faculty Feedback'), ('general', 'General Feedback'), ('complaint', 'Complaint')], default='semester', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
    ]
