# Generated by Django 5.2.12 on 2026-04-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_timetable_approved_at_timetable_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='timetable',
            name='hod_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
