# Generated by Django 5.2.12 on 2026-04-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_timetable_approval_status_timetable_hod_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rework_assigned', 'Rework Assigned'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
