# Generated by Django 4.2 on 2026-05-03 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0022_placementdrive_placementoffer_placementmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementoffer',
            old_name='offered_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='placementoffer',
            name='offer_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementoffer',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementoffer',
            name='salary_offered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='placementoffer',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('first_round_cleared', 'First Round Cleared'), ('second_round_cleared', 'Second Round Cleared'), ('third_round_cleared', 'Third Round Cleared'), ('placed', 'Placed'), ('rejected', 'Rejected')], default='applied', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='placementoffer',
            unique_together={('student', 'drive')},
        ),
        migrations.CreateModel(
            name='PlacementStudentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.CharField(choices=[('first', 'First Round'), ('second', 'Second Round'), ('third', 'Third Round'), ('final', 'Final Round')], max_length=20)),
                ('cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'drive', 'round_number')},
            },
        ),
        migrations.AddField(
            model_name='placementoffer',
            name='rounds_cleared',
            field=models.ManyToManyField(blank=True, related_name='offers', to='students.placementstudentround'),
        ),
    ]
